### ISSUE TITLE
Could we have a test phone number to send ProofMode bundles to?

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#5]
This issue aims to be the place to discuss some aspects of the backend of the _Signal x ProofMode_ integration project.

One of the user stories for the MVP is sending a Bundle (media + proofs) to a specific target ("relay bot" in Mural?) so as to trigger Starling-specific preservation and registration workflows:

> A user can easily take a picture or record a video in-app, and share that with a contact with any associated proof.

**Comment by YurkoWasHere** [comment]
`signald` the core of the starling signal bot has gone through some updates and no longer runs on our infrastructure due to an error that references Intel's recent security vulnerability

`[java.io](http://java.io/).IOException: [java.security](http://java.security/).SignatureException: Quote status is: SW_HARDENING_NEEDED and advisories are: [INTEL-SA-00334, INTEL-SA-00615]`

I have looked if there is any way around it and left some notes with the developer of `signald` however there is no ETA on this being fixed.

As a work around I will spend a bit of time to see if i can find a work around by  running `signald` on a CPU that is not affected (either much older before this bug was introduced or older after its been squashed)

I have stressed this is a work around no guarantee of stability or even success.

**Comment by basilesimon** [comment]
[The `signald` ingestor](https://github.com/starlinglab/signal_bot) is back up and running. The bot phone number is `+16474788566`.

It will reply ❌ when the bundle it receives is invalid, and 💾 when valid.

**Comment by YurkoWasHere** [comment]
To be clear 💾 Just means the file was sent for processing, it does not validate the file itself.
